steps:
# ------------------------------------------------------------
# Build training image
# ------------------------------------------------------------
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build training image'
  env:
    - DOCKER_BUILDKIT=1
  args:
    - build
    - -t
    - europe-west1-docker.pkg.dev/group-120/mlops-group120/train:latest
    - -f
    - dockerfiles/train.dockerfile
    - .

# ------------------------------------------------------------
# Push image
# ------------------------------------------------------------
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push training image'
  args:
    - push
    - europe-west1-docker.pkg.dev/group-120/mlops-group120/train:latest

# ------------------------------------------------------------
# Submit Vertex AI job via config file
# ------------------------------------------------------------
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'Submit Vertex AI job'
  entrypoint: bash
  args:
    - -c
    - |
      gcloud ai custom-jobs create \
        --region=europe-west1 \
        --display-name=mlops-train-${BUILD_ID} \
        --config=cloud_config.yaml

# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#   id: 'Upload model to Vertex AI Registry'
#   args:
#     - gcloud
#     - ai
#     - models
#     - upload
#     - --region=europe-west1
#     - --display-name=train-model
#     - --artifact-uri=gs://ml-models-group120/train/versions/${BUILD_ID}
#     - --container-image-uri=europe-west1-docker.pkg.dev/group-120/mlops-group120/train:latest


options:
  logging: CLOUD_LOGGING_ONLY
