steps:
# ------------------------------------------------------------
# Build training image
# ------------------------------------------------------------
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build training image'
  env:
    - DOCKER_BUILDKIT=1
  args:
    - build
    - -t
    - europe-west1-docker.pkg.dev/group-120/mlops-group120/train:${BUILD_ID}
    - -f
    - dockerfiles/train.dockerfile
    - .

# ------------------------------------------------------------
# Push image
# ------------------------------------------------------------
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push training image'
  args:
    - push
    - europe-west1-docker.pkg.dev/group-120/mlops-group120/train:${BUILD_ID}

# ------------------------------------------------------------
# Submit Vertex AI job via config file
# ------------------------------------------------------------
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'Submit Vertex AI job'
  entrypoint: bash
  args:
    - -c
    - |
      gcloud ai custom-jobs create \
        --region=europe-west1 \
        --display-name=mlops-train-${BUILD_ID} \
        --config=cloud_config.yaml

options:
  logging: CLOUD_LOGGING_ONLY
