steps:
- name: "alpine"
  id: "Replace values in the training config"
  entrypoint: "sh"
  args:
    - '-c'
    - |
      apk add --no-cache gettext
      envsubst < cloud_config.yaml > cloud_config.yaml.tmp
      mv cloud_config.yaml.tmp cloud_config.yaml
  secretEnv: ['WANDB_API_KEY']

- name: 'alpine'
  id: "Show config"
  waitFor: ['Replace values in the training config']
  entrypoint: "sh"
  args:
    - '-c'
    - |
      cat cloud_config.yaml

- name: 'gcr.io/cloud-builders/docker'
  id: 'Build training image'
  env:
    - DOCKER_BUILDKIT=1
  args:
    - build
    - -t
    - europe-west1-docker.pkg.dev/group-120/mlops-group120/train:latest
    - -f
    - dockerfiles/train.dockerfile
    - .

# ------------------------------------------------------------
# Push image
# ------------------------------------------------------------
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push training image'
  args:
    - push
    - europe-west1-docker.pkg.dev/group-120/mlops-group120/train:latest

# ------------------------------------------------------------
# Submit Vertex AI job via config file
# ------------------------------------------------------------

- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Train on vertex AI'
  waitFor: ['Replace values in the training config']
  args: [
    'ai',
    'custom-jobs',
    'create',
    '--region',
    'europe-west1',
    '--display-name',
    'example-mlops-job',
    '--config',
    '${_VERTEX_TRAIN_CONFIG}',
  ]
substitutions:
  _VERTEX_TRAIN_CONFIG: 'cloud_config.yaml'
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/wandb-api-key/versions/latest
    env: 'WANDB_API_KEY'