FROM ghcr.io/astral-sh/uv:python3.12-bookworm

WORKDIR /app

COPY pyproject.toml uv.lock README.md ./
COPY src src/
COPY tasks.py .
COPY configshydra configshydra/
COPY tests/performancetests/locustfile.py tests/performancetests/locustfile.py/

ENV UV_LINK_MODE=copy
RUN --mount=type=cache,target=/root/.cache/uv uv sync

ENV PYTHONPATH=/app
COPY entrypoint.sh ./
RUN chmod +x ./entrypoint.sh

ENTRYPOINT ["./entrypoint.sh"]